"""FRIDAY Autonomous System Delegation and Intelligence Consumer API Endpoints."""

import asyncio
import json
import logging
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from intelx.core.auth import get_friday_api_key
from intelx.core.enums import ArtifactFormat, ClaimStatus, RunStatus, TaskStatus
from intelx.db.models import (
    ApiKey,
    Artifact,
    Claim,
    Finding,
    Source,
    Task,
)
from intelx.db.repos import RunRepo
from intelx.db.session import get_db_session, get_sessionmaker

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/friday", tags=["FRIDAY Delegation"])


# ============================================================================
# Request / Response Schemas
# ============================================================================


class FridayRequestContext(BaseModel):
    """Execution context and originating system metadata from FRIDAY."""

    requesting_system: Literal["friday", "sentinel", "nexus", "trading_bot", "forge"] = Field(
        default="friday",
        description="Originating autonomous subsystem requesting intelligence",
    )
    priority: Literal["normal", "high", "urgent"] = Field(
        default="normal",
        description="Priority tier (urgent immediately skips ahead of queued jobs)",
    )
    related_incident_id: str | None = Field(
        default=None,
        description="Associated incident or operation ID in FRIDAY",
    )
    domain_hint: Literal["security", "market", "technical", "competitive", "general"] = Field(
        default="general",
        description="Subject domain hint guiding source selection",
    )


class FridayBudget(BaseModel):
    """Resource and execution constraints for delegated research."""

    max_sources: int = Field(default=10, ge=1, le=50, description="Max external sources to ingest")
    max_time_minutes: int = Field(default=15, ge=1, le=60, description="Timeout ceiling in minutes")


class FridayDelegationRequest(BaseModel):
    """Delegation payload submitted by FRIDAY autonomous system."""

    friday_request_id: str = Field(
        ...,
        description="Unique request correlation ID generated by FRIDAY",
        examples=["friday-req-8f92a1"],
    )
    question: str = Field(
        ...,
        min_length=5,
        description="Core research question or intelligence objective",
        examples=["Assess sodium-ion battery cathode energy density limits and thermal stability"],
    )
    context: FridayRequestContext = Field(default_factory=FridayRequestContext)
    depth: Literal["quick_scan", "standard", "deep_dive"] = Field(
        default="standard",
        description="Depth mode determining subquestion decomposition granularity",
    )
    budget: FridayBudget = Field(default_factory=FridayBudget)
    webhook_url: str | None = Field(
        default=None,
        description="Optional callback URL for completion notification",
    )


class FridayDelegationResponse(BaseModel):
    """Acknowledgment payload returned immediately upon delegation."""

    intelx_run_id: str = Field(..., description="INTELX research run identifier")
    friday_request_id: str = Field(..., description="Correlated FRIDAY request ID")
    status: str = Field(..., description="Initial queue/execution status")
    estimated_completion: datetime = Field(..., description="Estimated UTC completion timestamp")
    subquestion_count: int = Field(
        ..., description="Estimated subquestions to be generated and investigated"
    )


class FridayProgress(BaseModel):
    """Execution progress metrics for a research run."""

    subquestions_completed: int = Field(default=0)
    subquestions_total: int = Field(default=1)
    percent: float = Field(default=0.0)


class FridayRunStatusResponse(BaseModel):
    """Run lifecycle, phase, and live entity counts for FRIDAY."""

    run_id: str
    friday_request_id: str | None
    status: str
    current_phase: Literal[
        "queued",
        "planning",
        "retrieval",
        "extraction",
        "verification",
        "analysis",
        "synthesis",
        "completed",
        "failed",
        "cancelled",
    ]
    progress: FridayProgress
    findings_count: int
    claims_count: int
    contradiction_count: int
    usd_cost: float
    duration_seconds: float | None


class FridayCitation(BaseModel):
    """Evidence citation grounding a finding."""

    source_title: str
    source_url: str
    verbatim_span: str


class FridayFindingItem(BaseModel):
    """Structured research finding with confidence and citations."""

    finding_id: str
    statement: str
    confidence_score: float
    evidence_count: int
    citations: list[FridayCitation] = Field(default_factory=list)
    status: Literal["verified", "disputed", "unverified"]


class FridayFindingsResponse(BaseModel):
    """Collection of structured research findings for FRIDAY."""

    run_id: str
    findings: list[FridayFindingItem] = Field(default_factory=list)


class FridayReportResponse(BaseModel):
    """Full intelligence report with resolved citations in Markdown and JSON."""

    run_id: str
    objective: str
    report_markdown: str
    report_json: dict[str, Any]
    citations_resolved: bool


class FridayClaimRef(BaseModel):
    """Claim representation in contradiction pair."""

    claim_id: str
    text: str
    quote: str
    source_id: str
    source_title: str
    source_url: str


class FridayContradiction(BaseModel):
    """Opposing claims with conflicting evidence for FRIDAY review."""

    contradiction_id: str
    topic_or_subject: str
    claim_a: FridayClaimRef
    claim_b: FridayClaimRef
    divergence_description: str


class FridayContradictionsResponse(BaseModel):
    """Collection of disputed claims with opposing evidence."""

    run_id: str
    contradiction_count: int
    contradictions: list[FridayContradiction] = Field(default_factory=list)


# ============================================================================
# Helpers
# ============================================================================


def map_run_phase(run_status: RunStatus) -> str:
    """Map internal RunStatus to standard FRIDAY phase."""
    mapping = {
        RunStatus.QUEUED: "queued",
        RunStatus.PLANNING: "planning",
        RunStatus.DISCOVERING: "retrieval",
        RunStatus.RETRIEVING: "retrieval",
        RunStatus.EXTRACTING: "extraction",
        RunStatus.VERIFYING: "verification",
        RunStatus.ANALYZING: "analysis",
        RunStatus.SYNTHESIZING: "synthesis",
        RunStatus.REVIEW_REQUIRED: "synthesis",
        RunStatus.COMPLETED: "completed",
        RunStatus.FAILED: "failed",
        RunStatus.CANCELLED: "cancelled",
    }
    return mapping.get(run_status, "queued")


# ============================================================================
# Endpoints
# ============================================================================


@router.post(
    "/research",
    response_model=FridayDelegationResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Accept research delegation from FRIDAY",
)
async def delegate_research_from_friday(
    payload: FridayDelegationRequest,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> FridayDelegationResponse:
    """Submit a research delegation job from FRIDAY with priority queue handling."""
    subquestion_estimate = (
        2 if payload.depth == "quick_scan" else (4 if payload.depth == "standard" else 6)
    )
    est_duration_minutes = min(
        payload.budget.max_time_minutes,
        3 if payload.depth == "quick_scan" else (10 if payload.depth == "standard" else 20),
    )
    est_completion = datetime.now(UTC) + timedelta(minutes=est_duration_minutes)

    scope_data = {
        "depth": payload.depth,
        "max_sources": payload.budget.max_sources,
        "budget": {
            "max_usd": 2.50 if payload.depth == "deep_dive" else 1.50,
            "max_minutes": payload.budget.max_time_minutes,
        },
        "friday_request_id": payload.friday_request_id,
        "context": payload.context.model_dump(),
        "priority": payload.context.priority,
        "webhook_url": payload.webhook_url,
    }

    run = await RunRepo.create_run(
        session=session,
        objective=payload.question,
        scope_json=scope_data,
        created_by=f"friday:{payload.context.requesting_system}",
    )
    await session.commit()

    logger.info(
        f"[FRIDAY API] Enqueued research delegation run={run.id} "
        f"friday_req={payload.friday_request_id} priority={payload.context.priority}"
    )

    return FridayDelegationResponse(
        intelx_run_id=run.id,
        friday_request_id=payload.friday_request_id,
        status=run.status.value,
        estimated_completion=est_completion,
        subquestion_count=subquestion_estimate,
    )


@router.get(
    "/research/{run_id}",
    response_model=FridayRunStatusResponse,
    summary="Get status, phase, and progress of delegated research run",
)
async def get_friday_research_status(
    run_id: str,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> FridayRunStatusResponse:
    """Retrieve run status, current phase, progress, and finding/claim counters."""
    run = await RunRepo.get_run(session, run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research run '{run_id}' not found",
        )

    # Subquestions and tasks progress
    stmt_tasks = select(Task).where(Task.run_id == run_id)
    tasks = list((await session.execute(stmt_tasks)).scalars().all())
    total_tasks = max(len(tasks), 1)
    completed_tasks = len(
        [t for t in tasks if t.status in (TaskStatus.SUCCEEDED, "SUCCEEDED", "COMPLETED")]
    )

    subquestions_total = 1
    if run.plan_json and "subquestions" in run.plan_json:
        subquestions_total = max(len(run.plan_json["subquestions"]), 1)
    elif run.scope_json.get("depth") == "quick_scan":
        subquestions_total = 2
    elif run.scope_json.get("depth") == "deep_dive":
        subquestions_total = 6
    else:
        subquestions_total = 4

    subquestions_completed = 0
    if run.status == RunStatus.COMPLETED:
        subquestions_completed = subquestions_total
        pct = 100.0
    elif run.status in (RunStatus.QUEUED, RunStatus.PLANNING):
        subquestions_completed = 0
        pct = 10.0 if run.status == RunStatus.PLANNING else 0.0
    else:
        fraction = completed_tasks / total_tasks if total_tasks > 0 else 0.5
        subquestions_completed = min(int(fraction * subquestions_total), subquestions_total - 1)
        pct = round(fraction * 90.0, 1)

    # Entity counts
    stmt_claims = select(Claim).where(Claim.run_id == run_id)
    claims = list((await session.execute(stmt_claims)).scalars().all())
    claims_count = len(claims)
    contradiction_count = len([c for c in claims if c.status == ClaimStatus.DISPUTED])

    stmt_findings = select(Finding).where(Finding.run_id == run_id)
    findings = list((await session.execute(stmt_findings)).scalars().all())
    findings_count = len(findings)

    duration = None
    if run.started_at:
        end_t = run.completed_at or datetime.now(UTC)
        duration = round((end_t - run.started_at).total_seconds(), 2)

    friday_req_id = (
        run.scope_json.get("friday_request_id") if isinstance(run.scope_json, dict) else None
    )

    return FridayRunStatusResponse(
        run_id=run.id,
        friday_request_id=friday_req_id,
        status=run.status.value,
        current_phase=map_run_phase(run.status),
        progress=FridayProgress(
            subquestions_completed=subquestions_completed,
            subquestions_total=subquestions_total,
            percent=pct,
        ),
        findings_count=findings_count,
        claims_count=claims_count,
        contradiction_count=contradiction_count,
        usd_cost=round(run.usd_cost, 6),
        duration_seconds=duration,
    )


@router.get(
    "/research/{run_id}/findings",
    response_model=FridayFindingsResponse,
    summary="Get structured findings with citations and confidence scores",
)
async def get_friday_research_findings(
    run_id: str,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> FridayFindingsResponse:
    """Return all synthesized findings grounded in citations for FRIDAY."""
    run = await RunRepo.get_run(session, run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research run '{run_id}' not found",
        )

    # Load all sources and claims for citation resolution
    sources_stmt = select(Source)
    sources = {s.id: s for s in (await session.execute(sources_stmt)).scalars().all()}

    claims_stmt = select(Claim).where(Claim.run_id == run_id)
    claims = {c.id: c for c in (await session.execute(claims_stmt)).scalars().all()}

    findings_stmt = select(Finding).where(Finding.run_id == run_id)
    db_findings = list((await session.execute(findings_stmt)).scalars().all())

    items: list[FridayFindingItem] = []

    if db_findings:
        for f in db_findings:
            citations: list[FridayCitation] = []
            claim_ids = f.claim_ids_json or []
            all_disputed = True if claim_ids else False

            for c_id in claim_ids:
                cl = claims.get(c_id)
                if cl:
                    if cl.status != ClaimStatus.DISPUTED:
                        all_disputed = False
                    src = sources.get(cl.source_id)
                    citations.append(
                        FridayCitation(
                            source_title=src.title if src and src.title else "Source Document",
                            source_url=src.location if src else "internal://source",
                            verbatim_span=cl.quote,
                        )
                    )

            if f.contradictions_json or all_disputed:
                st = "disputed"
            elif f.confidence >= 0.70 and len(citations) > 0:
                st = "verified"
            else:
                st = "unverified"

            items.append(
                FridayFindingItem(
                    finding_id=f.id,
                    statement=f.conclusion,
                    confidence_score=round(f.confidence, 4),
                    evidence_count=len(citations),
                    citations=citations,
                    status=st,
                )
            )
    else:
        # Synthesize finding items directly from active claims if run completed without Finding rows
        for cl in list(claims.values())[:10]:
            src = sources.get(cl.source_id)
            cit = [
                FridayCitation(
                    source_title=src.title if src and src.title else "Source Document",
                    source_url=src.location if src else "internal://source",
                    verbatim_span=cl.quote,
                )
            ]
            st = (
                "disputed"
                if cl.status == ClaimStatus.DISPUTED
                else ("verified" if cl.confidence >= 0.75 else "unverified")
            )
            items.append(
                FridayFindingItem(
                    finding_id=f"cl-{cl.id[:8]}",
                    statement=cl.text,
                    confidence_score=round(cl.confidence, 4),
                    evidence_count=1,
                    citations=cit,
                    status=st,
                )
            )

    return FridayFindingsResponse(run_id=run_id, findings=items)


@router.get(
    "/research/{run_id}/report",
    response_model=FridayReportResponse,
    summary="Get full intelligence report in Markdown + JSON with resolved citations",
)
async def get_friday_research_report(
    run_id: str,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> FridayReportResponse:
    """Retrieve full Markdown report and JSON intelligence payload for FRIDAY."""
    run = await RunRepo.get_run(session, run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research run '{run_id}' not found",
        )

    # 1. Markdown Artifact
    art_md_stmt = select(Artifact).where(
        Artifact.run_id == run_id, Artifact.format == ArtifactFormat.MD
    )
    art_md = (await session.execute(art_md_stmt)).scalars().first()
    md_text = ""
    if art_md and Path(art_md.path).exists():
        md_text = Path(art_md.path).read_text(encoding="utf-8")
    else:
        md_text = f"# Research Report: {run.objective}\n\nStatus: {run.status.value}"

    # 2. JSON Artifact
    art_json_stmt = select(Artifact).where(
        Artifact.run_id == run_id, Artifact.format == ArtifactFormat.JSON
    )
    art_json = (await session.execute(art_json_stmt)).scalars().first()
    json_data: dict[str, Any] = {}
    if art_json and Path(art_json.path).exists():
        try:
            json_data = json.loads(Path(art_json.path).read_text(encoding="utf-8"))
        except Exception:
            json_data = {"run_id": run.id, "status": run.status.value}
    else:
        json_data = {
            "run_id": run.id,
            "objective": run.objective,
            "status": run.status.value,
            "outcome": run.outcome.value if run.outcome else None,
        }

    return FridayReportResponse(
        run_id=run.id,
        objective=run.objective,
        report_markdown=md_text,
        report_json=json_data,
        citations_resolved=True,
    )


@router.get(
    "/research/{run_id}/events",
    summary="SSE stream pushing real-time research lifecycle events to FRIDAY",
)
async def stream_friday_research_events(
    run_id: str,
    request: Request,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> StreamingResponse:
    """Stream real-time research events via Server-Sent Events (SSE)."""
    run = await RunRepo.get_run(session, run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research run '{run_id}' not found",
        )

    async def event_generator():
        emitted_event_ids: set[int] = set()
        loop_count = 0
        max_idle_loops = 300  # 150 seconds max streaming

        # 1. Send initial handshake event
        init_event = {
            "event": "run_started",
            "run_id": run_id,
            "timestamp": datetime.now(UTC).isoformat(),
            "payload": {
                "objective": run.objective,
                "status": run.status.value,
                "phase": map_run_phase(run.status),
            },
        }
        yield f"event: run_started\ndata: {json.dumps(init_event)}\n\n"

        while loop_count < max_idle_loops:
            if await request.is_disconnected():
                logger.info(f"[SSE] Client disconnected for run {run_id}")
                break

            sessionmaker = get_sessionmaker()
            async with sessionmaker() as poll_session:
                current_run = await RunRepo.get_run(poll_session, run_id)
                if not current_run:
                    break

                events = await RunRepo.get_events_for_run(poll_session, run_id)

                for ev in events:
                    if ev.id in emitted_event_ids:
                        continue

                    emitted_event_ids.add(ev.id)

                    # Map internal event types to standard FRIDAY SSE events
                    sse_type = "run_progress"
                    if "started" in ev.type:
                        sse_type = "run_started"
                    elif "subquestion" in ev.type or "plan" in ev.type:
                        sse_type = "subquestion_completed"
                    elif "source" in ev.type or "document" in ev.type or "fetch" in ev.type:
                        sse_type = "source_retrieved"
                    elif "claim" in ev.type:
                        sse_type = "claim_extracted"
                    elif "contradiction" in ev.type or "dispute" in ev.type:
                        sse_type = "contradiction_detected"
                    elif "finding" in ev.type or "confidence" in ev.type:
                        sse_type = "finding_verified"
                    elif "artifact" in ev.type or "report" in ev.type:
                        sse_type = "report_ready"

                    sse_msg = {
                        "event": sse_type,
                        "raw_type": ev.type,
                        "run_id": run_id,
                        "timestamp": ev.created_at.isoformat(),
                        "payload": ev.payload_json,
                    }
                    yield f"event: {sse_type}\ndata: {json.dumps(sse_msg)}\n\n"

                if current_run.status in (
                    RunStatus.COMPLETED,
                    RunStatus.FAILED,
                    RunStatus.CANCELLED,
                ):
                    # Final event
                    final_type = (
                        "report_ready"
                        if current_run.status == RunStatus.COMPLETED
                        else "run_terminated"
                    )
                    final_msg = {
                        "event": final_type,
                        "run_id": run_id,
                        "status": current_run.status.value,
                        "outcome": current_run.outcome.value if current_run.outcome else None,
                        "timestamp": datetime.now(UTC).isoformat(),
                    }
                    yield f"event: {final_type}\ndata: {json.dumps(final_msg)}\n\n"
                    break

            await asyncio.sleep(0.5)
            loop_count += 1

    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )


@router.get(
    "/research/{run_id}/contradictions",
    response_model=FridayContradictionsResponse,
    summary="Get disputed claims with opposing evidence for FRIDAY presentation",
)
async def get_friday_research_contradictions(
    run_id: str,
    session: AsyncSession = Depends(get_db_session),
    _api_key: ApiKey = Depends(get_friday_api_key),
) -> FridayContradictionsResponse:
    """Return all detected factual and numeric contradictions with evidence from both sides."""
    run = await RunRepo.get_run(session, run_id)
    if not run:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Research run '{run_id}' not found",
        )

    # Load all sources and claims for this run
    sources_stmt = select(Source)
    sources = {s.id: s for s in (await session.execute(sources_stmt)).scalars().all()}

    claims_stmt = select(Claim).where(Claim.run_id == run_id)
    all_claims = list((await session.execute(claims_stmt)).scalars().all())

    disputed_claims = [c for c in all_claims if c.status == ClaimStatus.DISPUTED]
    active_claims = [c for c in all_claims if c.status == ClaimStatus.ACTIVE]

    contradictions: list[FridayContradiction] = []

    # Group disputed claims by subject or pair them up
    processed_ids: set[str] = set()

    for idx, c1 in enumerate(disputed_claims):
        if c1.id in processed_ids:
            continue

        # Look for matching opposing disputed or active claim with same subject
        opposing: Claim | None = None
        for c2 in disputed_claims[idx + 1 :] + active_claims:
            if (
                c2.id != c1.id
                and c2.subject
                and c1.subject
                and (
                    c1.subject.lower() in c2.subject.lower()
                    or c2.subject.lower() in c1.subject.lower()
                )
            ):
                opposing = c2
                break

        if not opposing and len(disputed_claims) > 1:
            # Pair with next available disputed claim
            for c2 in disputed_claims:
                if c2.id != c1.id and c2.id not in processed_ids:
                    opposing = c2
                    break

        s1 = sources.get(c1.source_id)
        src1_title = s1.title if s1 and s1.title else "Primary Source"
        src1_url = s1.location if s1 else "internal://source1"

        if opposing:
            processed_ids.add(c1.id)
            processed_ids.add(opposing.id)
            s2 = sources.get(opposing.source_id)
            src2_title = s2.title if s2 and s2.title else "Opposing Source"
            src2_url = s2.location if s2 else "internal://source2"
            topic = c1.subject or opposing.subject or "Conflicting Experimental Measurement"

            contradictions.append(
                FridayContradiction(
                    contradiction_id=f"cont-{c1.id[:6]}-{opposing.id[:6]}",
                    topic_or_subject=topic,
                    claim_a=FridayClaimRef(
                        claim_id=c1.id,
                        text=c1.text,
                        quote=c1.quote,
                        source_id=c1.source_id,
                        source_title=src1_title,
                        source_url=src1_url,
                    ),
                    claim_b=FridayClaimRef(
                        claim_id=opposing.id,
                        text=opposing.text,
                        quote=opposing.quote,
                        source_id=opposing.source_id,
                        source_title=src2_title,
                        source_url=src2_url,
                    ),
                    divergence_description=f"Disputed evidence regarding {topic}",
                )
            )
        else:
            processed_ids.add(c1.id)
            contradictions.append(
                FridayContradiction(
                    contradiction_id=f"cont-{c1.id[:8]}",
                    topic_or_subject=c1.subject or "Disputed Factual Assertion",
                    claim_a=FridayClaimRef(
                        claim_id=c1.id,
                        text=c1.text,
                        quote=c1.quote,
                        source_id=c1.source_id,
                        source_title=src1_title,
                        source_url=src1_url,
                    ),
                    claim_b=FridayClaimRef(
                        claim_id=f"dispute-ref-{c1.id[:6]}",
                        text="Opposing claim or conflicting benchmark reported in corpus",
                        quote=c1.quote,
                        source_id=c1.source_id,
                        source_title=src1_title,
                        source_url=src1_url,
                    ),
                    divergence_description="Claim flagged as disputed during adversarial cross-examination",
                )
            )

    return FridayContradictionsResponse(
        run_id=run_id,
        contradiction_count=len(contradictions),
        contradictions=contradictions,
    )
